import { ADMIN_BASE_URL, GENERAL_BASE_URL, PICKLIST_BASE_URL } from 'src/utils/BaseUrls';

export const ARTIST_ENDPOINTS = {
  AddArtist: `${ADMIN_BASE_URL}/artist-register`,
  getArtistDetail: `${ADMIN_BASE_URL}/get-register-artist`,
  activateArtist: `${ADMIN_BASE_URL}/activate-artist`,
  getAllArtist: `${ADMIN_BASE_URL}/get-all-completed-artists`,
  getAllArtistInDatabase: `${ADMIN_BASE_URL}/get-all-artists`,
  getAllBecomeArtist: `${ADMIN_BASE_URL}/get-artist-request-list`,
  getAllPendingArtist: `${ADMIN_BASE_URL}/get-artist-pending-list`,
  createNewUser: `${ADMIN_BASE_URL}/create-new-user`,
  getuser: `${ADMIN_BASE_URL}/get-user`,
  suspendedArtist: `${ADMIN_BASE_URL}/suspended-list`,
  suspendArtist: `${ADMIN_BASE_URL}/suspend-artist`,
  rejectRequest: `${ADMIN_BASE_URL}/reject-artist-request`,
  banRequest: `${ADMIN_BASE_URL}/ban-artist-request`,
  unSuspendArtist: `${ADMIN_BASE_URL}/unsuspend-artist`,
  chnageArtistPasswoed: `${ADMIN_BASE_URL}/change-artist-password`,
  addArtwork: `${ADMIN_BASE_URL}/add-artwork`,
  publishArtwork: `${ADMIN_BASE_URL}/publish-artwork`,
  getArtworkById: `${ADMIN_BASE_URL}/get-artwork`,
  getArtWorkList: `${ADMIN_BASE_URL}/get-artwork-list`,
  getArtistById: `${ADMIN_BASE_URL}/get-artist-by-id`,
  getUserById: `${ADMIN_BASE_URL}/get-user-by-id`,
  getUserByQueryInput: `${ADMIN_BASE_URL}/get-user-by-query-input`,
  removeArtWorkList: `${ADMIN_BASE_URL}/remove-artwork`,
  getAllTickets: `${ADMIN_BASE_URL}/get-all-tickets`,
  replyTicket: `${ADMIN_BASE_URL}/reply-ticket`,
  getTicketReply: `${ADMIN_BASE_URL}/get-ticket-replies`,
  addIncident: `${ADMIN_BASE_URL}/add-incident`,
  addTicket: `${ADMIN_BASE_URL}/add-ticket`,
  getAllIncident: `${ADMIN_BASE_URL}/get-all-incidents`,
  addInsignia: `${ADMIN_BASE_URL}/add-insignia`,
  getInsigniaById: `${ADMIN_BASE_URL}/get-insignia`,
  getAllInsignia: `${ADMIN_BASE_URL}/get-all-insignia`,
  deleteInsignia: `${ADMIN_BASE_URL}/delete-insignia`,
  addCatalog: `${ADMIN_BASE_URL}/add-catalog`,
  getAllCatalog: `${ADMIN_BASE_URL}/get-all-catalog`,
  getCatalogById: `${ADMIN_BASE_URL}/get-catalog-by-id`,
  addFAQ: `${ADMIN_BASE_URL}/add-faq`,
  getAllFAQ: `${ADMIN_BASE_URL}/get-all-faq`,
  getFAQById: `${ADMIN_BASE_URL}/get-faq-by-id`,
};

export const USER_ENDPOINTS = {
  getUserList: `${ADMIN_BASE_URL}/get-all-users`,
};

export const GENERAL_ENDPOINTS = {
  getDiscipline: `${GENERAL_BASE_URL}/list-discipline`,
  getStyle: `${GENERAL_BASE_URL}/list-style`,
  getTechnic: `${GENERAL_BASE_URL}/list-technic`,
  getTheme: `${GENERAL_BASE_URL}/list-theme`,
  getMedia: `${GENERAL_BASE_URL}/list-media`,
  addDiscipline: `${GENERAL_BASE_URL}/add-discipline`,
  getDisciplineById: `${GENERAL_BASE_URL}/get-discipline`,
  addStyle: `${GENERAL_BASE_URL}/add-style`,
  getStyleById: `${GENERAL_BASE_URL}/get-style`,
  addTheme: `${GENERAL_BASE_URL}/add-theme`,
  getThemeById: `${GENERAL_BASE_URL}/get-theme`,
  addTechnic: `${GENERAL_BASE_URL}/add-technic`,
  getTechnicById: `${GENERAL_BASE_URL}/get-technic`,
  addMedia: `${GENERAL_BASE_URL}/add-media`,
  getMediaById: `${GENERAL_BASE_URL}/get-media`,
  deleteTheme: `${GENERAL_BASE_URL}/delete-theme`,
  deleteTechnic: `${GENERAL_BASE_URL}/delete-technic`,
  deleteDiscipline: `${GENERAL_BASE_URL}/delete-discipline`,
  deleteStyle: `${GENERAL_BASE_URL}/delete-style`,
  deleteMedia: `${GENERAL_BASE_URL}/delete-media`,
};

export const PICKLIST_ENDPOINTS = {
  addPicklist: `${PICKLIST_BASE_URL}/add-picklist`,
  getPicklists: `${PICKLIST_BASE_URL}/get-picklist`,
  getPicklistById: `${PICKLIST_BASE_URL}/get-picklist-by-id`,
  updatePicklist: `${PICKLIST_BASE_URL}/update-picklist`,
};
