import { get } from 'http';
import {
  ADMIN_BASE_URL,
  GENERAL_BASE_URL,
  PICKLIST_BASE_URL,
  ORDER_BASE_URL,
  EMAIL_BASE_URL,
  CIRCLE_BASE_URL,
} from 'src/utils/BaseUrls';

export const ARTIST_ENDPOINTS = {
  AddArtist: `${ADMIN_BASE_URL}/artist-register`,
  getArtistDetail: `${ADMIN_BASE_URL}/get-register-artist`,
  activateArtist: `${ADMIN_BASE_URL}/activate-artist`,
  getAllArtist: `${ADMIN_BASE_URL}/get-all-completed-artists`,
  getAllArtistInDatabase: `${ADMIN_BASE_URL}/get-all-artists`,
  getAllBecomeArtist: `${ADMIN_BASE_URL}/get-artist-request-list`,
  getAllPendingArtist: `${ADMIN_BASE_URL}/get-artist-pending-list`,
  createNewUser: `${ADMIN_BASE_URL}/create-new-user`,
  suspendedArtist: `${ADMIN_BASE_URL}/suspended-list`,
  suspendArtist: `${ADMIN_BASE_URL}/suspend-artist`,
  rejectRequest: `${ADMIN_BASE_URL}/reject-artist-request`,
  unRejectRequest: `${ADMIN_BASE_URL}/unreject-artist-request`,
  banRequest: `${ADMIN_BASE_URL}/ban-artist-request`,
  unBanRequest: `${ADMIN_BASE_URL}/unban-artist-request`,
  unSuspendArtist: `${ADMIN_BASE_URL}/unsuspend-artist`,
  chnageArtistPasswoed: `${ADMIN_BASE_URL}/change-artist-password`,
  addArtwork: `${ADMIN_BASE_URL}/add-artwork`,
  publishArtwork: `${ADMIN_BASE_URL}/publish-artwork`,
  getArtworkById: `${ADMIN_BASE_URL}/get-artwork`,
  getCatalogsName: `${ADMIN_BASE_URL}/get-catalogs-name`,
  getArtWorkList: `${ADMIN_BASE_URL}/get-artwork-list`,
  getArtistById: `${ADMIN_BASE_URL}/get-artist-by-id`,
  getUserById: `${ADMIN_BASE_URL}/get-user-by-id`,
  removeArtWorkList: `${ADMIN_BASE_URL}/remove-artwork`,
  movePending: `${ADMIN_BASE_URL}/move-to-pending`,
  getAllTickets: `${ADMIN_BASE_URL}/get-all-tickets`,
  getTicketDetail: `${ADMIN_BASE_URL}/get-ticket`,
  replyTicket: `${ADMIN_BASE_URL}/reply-ticket`,
  getTicketReply: `${ADMIN_BASE_URL}/get-ticket-replies`,
  addIncident: `${ADMIN_BASE_URL}/add-incident`,
  addTicket: `${ADMIN_BASE_URL}/add-ticket`,
  getAllIncident: `${ADMIN_BASE_URL}/get-all-incidents`,
  addInsignia: `${ADMIN_BASE_URL}/add-insignia`,
  getInsigniaById: `${ADMIN_BASE_URL}/get-insignia`,
  getAllInsignia: `${ADMIN_BASE_URL}/get-all-insignia`,
  deleteInsignia: `${ADMIN_BASE_URL}/delete-insignia`,
  addCatalog: `${ADMIN_BASE_URL}/add-catalog`,
  getAllCatalog: `${ADMIN_BASE_URL}/get-all-catalog`,
  getCatalogById: `${ADMIN_BASE_URL}/get-catalog-by-id`,
  deleteCatalog: `${ADMIN_BASE_URL}/delete-catalog`,
  addCollection: `${ADMIN_BASE_URL}/add-collection`,
  getAllCollection: `${ADMIN_BASE_URL}/get-all-collection`,
  getCatalogList: `${ADMIN_BASE_URL}/get-catalog-list`,
  getCollectionById: `${ADMIN_BASE_URL}/get-collection-by-id`,
  deleteArtworkFromCollection: `${ADMIN_BASE_URL}/delete-artwork-from-collection`,
  deleteCollection: `${ADMIN_BASE_URL}/delete-collection`,
  restoreCollection: `${ADMIN_BASE_URL}/restore-collection`,
  addFAQ: `${ADMIN_BASE_URL}/add-faq`,
  getAllFAQ: `${ADMIN_BASE_URL}/get-all-faq`,
  getFAQById: `${ADMIN_BASE_URL}/get-faq-by-id`,
  addKB: `${ADMIN_BASE_URL}/add-kb`,
  getAllKB: `${ADMIN_BASE_URL}/get-all-kb`,
  getKBById: `${ADMIN_BASE_URL}/get-kb-by-id`,
  getUserList: `${ADMIN_BASE_URL}/get-all-users`,
  getUserOnSearch: `${ADMIN_BASE_URL}/get-user-on-search`,
  getUser: `${ADMIN_BASE_URL}/get-user`,
  getNotification: `${ADMIN_BASE_URL}/get-notification-history`,
  validateArtwork: `${ADMIN_BASE_URL}/validate-artwork`,
  getSearchedArtwork: `${ADMIN_BASE_URL}/get-search-artwork`,
  getSearchedCollection: `${ADMIN_BASE_URL}/get-search-collection`,
  addSeries: `${ADMIN_BASE_URL}/add-series-to-artist`,
  deleteSeries: `${ADMIN_BASE_URL}/delete-series`,
  getSeriesList: `${ADMIN_BASE_URL}/get-series-list`,
  getReviewArtist: `${ADMIN_BASE_URL}/get-review-artist-detail`,
  getReviewArtwork: `${ADMIN_BASE_URL}/get-review-artwork`,
  approveArtistChanges: `${ADMIN_BASE_URL}/approve-changes`,
  approveArtworkChanges: `${ADMIN_BASE_URL}/approve-artwork-changes`,
  revalidateArtist: `${ADMIN_BASE_URL}/revalidate-artist`,
  getIncidentById: `${ADMIN_BASE_URL}/get-incident-by-id`,
  addPlan: `${ADMIN_BASE_URL}/add-plan`,
  getAllPlan: `${ADMIN_BASE_URL}/get-all-plans`,
  getPlanById: `${ADMIN_BASE_URL}/get-plan-by-id`,
  addCoupon: `${ADMIN_BASE_URL}/add-coupon`,
  getAllCoupon: `${ADMIN_BASE_URL}/get-all-coupons`,
  getCouponById: `${ADMIN_BASE_URL}/get-coupon-by-id`,
  getHomeArtwork: `${ADMIN_BASE_URL}/get-admin-home-artworks`,
  addHomeArtwork: `${ADMIN_BASE_URL}/add-home-artwork`,
  getHomeArtworkById: `${ADMIN_BASE_URL}/get-home-artwork`,
  deleteHomeArtworkItem: `${ADMIN_BASE_URL}/delete-item`,
  addFile: `${ADMIN_BASE_URL}/upload-json`,
  getFiles: `${ADMIN_BASE_URL}/get-files`,
  getAllCarousel: `${ADMIN_BASE_URL}/get-all-carousel`,
  getCarousel: `${ADMIN_BASE_URL}/get-carousel-by-id`,
  deleteCarousel: `${ADMIN_BASE_URL}/delete-carousel`,
  addCarousel: `${ADMIN_BASE_URL}/add-carousel`,
  activateCarousel: `${ADMIN_BASE_URL}/activate-carousel`,
  getSubscriptions: `${ADMIN_BASE_URL}/get-subscriptions`,
  addVisualizer: `${ADMIN_BASE_URL}/add-visualize`,
  getAllVisualize: `${ADMIN_BASE_URL}/get-all-visualize`,
  getVisualizeById: `${ADMIN_BASE_URL}/get-visualize`,

  downloadArtwork: `${ADMIN_BASE_URL}/download-artwork-list`,
  downloadAllArtist: `${ADMIN_BASE_URL}/download-all-artist-list`,
  downloadDiscipline: `${ADMIN_BASE_URL}/download-discipline-list`,
  downloadCategory: `${ADMIN_BASE_URL}/download-category-list`,
  downloadPicklist: `${ADMIN_BASE_URL}/download-picklist`,
  downloadInsignia: `${ADMIN_BASE_URL}/download-insignia-list`,
  downloadFAQ: `${ADMIN_BASE_URL}/download-faq-list`,
  downloadKB: `${ADMIN_BASE_URL}/download-kb-list`,
  downloadCoupon: `${ADMIN_BASE_URL}/download-coupon-list`,
};

export const USER_ENDPOINTS = {
  getUserList: `${ADMIN_BASE_URL}/get-all-users`,
};

export const EMAIL_ENDPOINTS = {
  addEmail: `${EMAIL_BASE_URL}/add-email-type`,
  getEmail: `${EMAIL_BASE_URL}/get-email-types`,
  getEmailById: `${EMAIL_BASE_URL}/get-email-type-by-id`,
};

export const CIRCLE_ENDPOINTS = {
  addCircle: `${CIRCLE_BASE_URL}/add-circle`,
  getCircle: `${CIRCLE_BASE_URL}/get-circle`,
  allCircles: `${CIRCLE_BASE_URL}/get-all-circles`,
  getMembers: `${CIRCLE_BASE_URL}/get-all-follower-circles`,
  deleteCircle: `${CIRCLE_BASE_URL}/delete-circle`,
};

export const GENERAL_ENDPOINTS = {
  getDiscipline: `${GENERAL_BASE_URL}/list-discipline`,
  getStyle: `${GENERAL_BASE_URL}/list-style`,
  getTechnic: `${GENERAL_BASE_URL}/list-technic`,
  getTheme: `${GENERAL_BASE_URL}/list-theme`,
  getMedia: `${GENERAL_BASE_URL}/list-media`,
  addDiscipline: `${GENERAL_BASE_URL}/add-discipline`,
  getDisciplineById: `${GENERAL_BASE_URL}/get-discipline`,
  addStyle: `${GENERAL_BASE_URL}/add-style`,
  getStyleById: `${GENERAL_BASE_URL}/get-style`,
  addTheme: `${GENERAL_BASE_URL}/add-theme`,
  getThemeById: `${GENERAL_BASE_URL}/get-theme`,
  addTechnic: `${GENERAL_BASE_URL}/add-technic`,
  getTechnicById: `${GENERAL_BASE_URL}/get-technic`,
  addMedia: `${GENERAL_BASE_URL}/add-media`,
  getMediaById: `${GENERAL_BASE_URL}/get-media`,
  deleteTheme: `${GENERAL_BASE_URL}/delete-theme`,
  deleteTechnic: `${GENERAL_BASE_URL}/delete-technic`,
  deleteDiscipline: `${GENERAL_BASE_URL}/delete-discipline`,
  deleteStyle: `${GENERAL_BASE_URL}/delete-style`,
  deleteMedia: `${GENERAL_BASE_URL}/delete-media`,
};

export const PICKLIST_ENDPOINTS = {
  addPicklist: `${PICKLIST_BASE_URL}/add-picklist`,
  getPicklists: `${PICKLIST_BASE_URL}/get-picklist`,
  getPicklistById: `${PICKLIST_BASE_URL}/get-picklist-by-id`,
  updatePicklist: `${PICKLIST_BASE_URL}/update-picklist`,
  deletePicklist: `${PICKLIST_BASE_URL}/delete-picklist`,
  updatePicklistName: `${PICKLIST_BASE_URL}/update-picklist-name`,
};

export const ORDER_ENDPOINTS = {
  getSubscriptionOrder: `${ORDER_BASE_URL}/get-subscription-order`,
  getPurchaseOrder: `${ORDER_BASE_URL}/get-purchase-order`,
  getAllOrders: `${ORDER_BASE_URL}/get-all-orders`,
  getOrderDetail: `${ORDER_BASE_URL}/get-admin-order-detail`,
};
