export const ArtworkList = [
  {
    artworkName: 'Starry Night',
    artworkType: 'Painting',
    commercializationWay: 'Auction',
    artistName: 'Vincent van Gogh',
    publishDate: '1889-06-01',
    status: 'published',
    catalog: 'VVG-001',
  },
  {
    artworkName: 'The Persistence of Memory',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Salvador Dalí',
    publishDate: '1931-04-01',
    status: 'draft',
    catalog: 'SD-002',
  },
  {
    artworkName: 'The Scream',
    artworkType: 'Painting',
    commercializationWay: 'Auction',
    artistName: 'Edvard Munch',
    publishDate: '1893-01-01',
    status: 'failed',
    catalog: 'EM-003',
  },
  {
    artworkName: 'Mona Lisa',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Leonardo da Vinci',
    publishDate: '1503-06-01',
    status: 'published',
    catalog: 'LD-004',
  },
  {
    artworkName: 'Girl with a Pearl Earring',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Johannes Vermeer',
    publishDate: '1665-01-01',
    status: 'draft',
    catalog: 'JV-005',
  },
  {
    artworkName: 'The Last Supper',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Leonardo da Vinci',
    publishDate: '1498-01-01',
    status: 'published',
    catalog: 'LD-006',
  },
  {
    artworkName: 'The Kiss',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Gustav Klimt',
    publishDate: '1907-01-01',
    status: 'failed',
    catalog: 'GK-007',
  },
  {
    artworkName: 'Water Lilies',
    artworkType: 'Painting',
    commercializationWay: 'Auction',
    artistName: 'Claude Monet',
    publishDate: '1916-01-01',
    status: 'published',
    catalog: 'CM-008',
  },
  {
    artworkName: 'The Night Watch',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Rembrandt van Rijn',
    publishDate: '1642-01-01',
    status: 'draft',
    catalog: 'RR-009',
  },
  {
    artworkName: 'The Birth of Venus',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Sandro Botticelli',
    publishDate: '1484-01-01',
    status: 'failed',
    catalog: 'SB-010',
  },
  {
    artworkName: 'Guernica',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Pablo Picasso',
    publishDate: '1937-01-01',
    status: 'published',
    catalog: 'PP-011',
  },
  {
    artworkName: 'The Creation of Adam',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Michelangelo',
    publishDate: '1512-01-01',
    status: 'draft',
    catalog: 'M-012',
  },
  {
    artworkName: 'American Gothic',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Grant Wood',
    publishDate: '1930-01-01',
    status: 'published',
    catalog: 'GW-013',
  },
  {
    artworkName: 'The Great Wave off Kanagawa',
    artworkType: 'Print',
    commercializationWay: 'Auction',
    artistName: 'Hokusai',
    publishDate: '1831-01-01',
    status: 'failed',
    catalog: 'H-014',
  },
  {
    artworkName: 'The Arnolfini Portrait',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Jan van Eyck',
    publishDate: '1434-01-01',
    status: 'draft',
    catalog: 'JE-015',
  },
  {
    artworkName: "Campbell's Soup Cans",
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Andy Warhol',
    publishDate: '1962-01-01',
    status: 'published',
    catalog: 'AW-016',
  },
  {
    artworkName: 'The School of Athens',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Raphael',
    publishDate: '1511-01-01',
    status: 'draft',
    catalog: 'R-017',
  },
  {
    artworkName: 'Las Meninas',
    artworkType: 'Painting',
    commercializationWay: 'Museum',
    artistName: 'Diego Velázquez',
    publishDate: '1656-01-01',
    status: 'failed',
    catalog: 'DV-018',
  },
  {
    artworkName: 'No. 5, 1948',
    artworkType: 'Painting',
    commercializationWay: 'Auction',
    artistName: 'Jackson Pollock',
    publishDate: '1948-01-01',
    status: 'published',
    catalog: 'JP-019',
  },
  {
    artworkName: 'Café Terrace at Night',
    artworkType: 'Painting',
    commercializationWay: 'Gallery',
    artistName: 'Vincent van Gogh',
    publishDate: '1888-01-01',
    status: 'draft',
    catalog: 'VVG-020',
  },
];
