export interface ArtistDetailType {
  name: string;
  About: string;
  ArtworkModule: string;
  accountId: string;
  artistName: string;
  artistSurname1: string;
  artistSurname2: string;
  highlights: string;
  cvData: cvData[];
  insignia: [];
  currency: string;
  previousRevalidationDate: [];
  managerAddress: string;

  nickName?: string;
  ArtistId: string;
  country?: object | null;
  createDate?: string;
  language: string[];
  zipCode: string;
  city: string;
  state: string;
  residentialAddress: string;
  phone: string;
  email: string;
  gender: string;
  notes?: string;
  ProductStatus: string;
  year: string;
  about: string;
  ArtistCategory: ArtistCategory[];
  discipline: [];
  Type: string;
  taxNumber: string;
  taxLegalName: string;
  taxAddress: string;
  taxZipCode: string;
  taxCity: string;
  taxProvince: string;
  taxCountry?: object | null;
  taxEmail: string;
  taxPhone: string;
  taxBankIBAN: string;
  vatAmount: string;
  taxBankName: string;
  CustomOrder: string;
  PublishingCatalog: string;
  ArtistFees: string;
  artistLevel: string;
  artProvider: string;
  ArtistPlus?: string;
  scorePlatform: string;
  scoreProfessional: string;
  MinNumberOfArtwork: string;
  MaxNumberOfArtwork: string;
  Description: string;
  Location?: string;
  Scope?: string;
  logName: string;
  logAddress: string;
  logZipCode: string;
  logCity: string;
  logProvince: string;
  logCountry?: object | null;
  documents: any[];
  profileImage: any;
  additionalImage: any[];
  inProcessImage: any;
  mainVideo: any;
  additionalVideo: any[];
  extraInfo1: string;
  extraInfo2: string;
  extraInfo3: string;
  profileStatus: string;
  lastRevalidationDate: string;
  nextRevalidationDate: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  emergencyContactEmail: string;
  emergencyContactAddress: string;
  emergencyContactRelation: string;
  managerName: string;
  managerArtistContactTo?: string;
  managerArtistPhone: string;
  managerArtistEmail: string;
  address: string;
  managerZipCode: string;
  managerCity: string;
  managerState: string;
  managerCountry: string;
  managerArtistLanguage: string[];
  managerArtistGender: string;
  logEmail: string;
  logPhone: string;
  logNotes?: string;
  intTags: string[];
  extTags: string[];
  link: [];

  //-----artsistlist-----
  _id: any;
  uploadImage: any;
  profile: any;
  artistId: string;
  isActivated: Boolean;
  createdAt: string;
  userId: string;
}

interface cvData {
  year: string;
  Type: string;
  Description: string;
  Location?: string;
  Scope?: string;
}

interface ArtistCategory {
  catagoryone: string;
  styleone: string;
  styletwo: string;
}

export interface ArtistListType {
  _id: string;
  avatar: string;
  discipline: any[];
  links: any[];
  documents: any[];
  isActivated: Boolean;
  profileStatus: string;
  userId?: string;
  artistId: string;
  artistName: string;
  artistSurname1: string;
  artistSurname2: string;
  isArtistRequestStatus: string;
  uploadImage: any;
  profile: any;
  email: string;
  phone: string;
  createdAt: string;
  city: string;
  state: string;
  zipCode: string;
  country?: string;
  incGroup: string;
  severity: string;
  title: string;
  incType: string;
  status: string;
  initTime: string;
  endTime: string;
  nextRevalidationDate: string;
  lastRevalidationDate: string;
}

export interface ArtistDisciplineType {
  disciplineImage: any;
  emailType: string;
  _id: string;
  mediaName: string;
  disciplineSpanishName: string;
  disciplineDescription: string;
  spanishMediaName: string;
  disciplineName: string;
  styleName: string;
  artworkName: string;
  artworkId: string;
  img: string;
  spanishStyleName: string;
  technicName: string;
  spanishTechnicName: string;
  themeName: string;
  spanishThemeName: string;
  createdAt: string;
  description: string;
  name: string;
  spanishName: string;
  discipline: Array<string>;
  isDeleted: Boolean;
  insigniaImage: any;
  credentialName: string;
  credentialPriority: string;
  credentialGroup: string;
  isActive: Boolean;
}
